export interface DietMeal {
  mealType: 'breakfast' | 'snack_morning' | 'lunch' | 'snack_evening' | 'dinner';
  name: string;
  items: string[];
  portion: string;
  calories: number;
  protein: number;
  carbs: number;
  fats: number;
  icon: string;
  tips?: string;
}

export interface DietDay {
  dayName: string; // e.g. 'Monday'
  focus: string;
  totalCalories: number;
  totalProtein: number;
  totalCarbs: number;
  totalFats: number;
  meals: DietMeal[];
}

export interface WeeklyDietPlan {
  id: string;
  name: string;
  tagline: string;
  locality: 'tamilnadu' | 'telugu' | 'kannada' | 'south_general' | 'north' | 'western' | 'custom';
  localityLabel: string;
  targetWeightLossRate: string; // e.g. '0.5 kg / week'
  weeklyLossKg: number;        // e.g. 0.5
  avgDailyCalories: number;
  avgDailyProtein: number;
  avgDailyCarbs: number;
  avgDailyFats: number;
  dietType: 'Non-Veg' | 'Veg' | 'Eggitarian' | 'Vegan' | 'Keto' | 'Millets';
  suitableForSex?: 'all' | 'male' | 'female';
  suitableAgeRange?: string;
  icon: string;
  colorClass: string;
  borderClass: string;
  isCustom?: boolean;
  days: DietDay[];
}

export const STORAGE_CUSTOM_DIETS_KEY = 'shadow_custom_diet_plans_v1';

export function getCustomDietPlans(): WeeklyDietPlan[] {
  if (typeof window === 'undefined') return [];
  try {
    const raw = localStorage.getItem(STORAGE_CUSTOM_DIETS_KEY);
    if (raw) return JSON.parse(raw);
  } catch (e) {
    console.error('Error reading custom diet plans:', e);
  }
  return [];
}

export function saveCustomDietPlan(plan: WeeklyDietPlan): WeeklyDietPlan[] {
  if (typeof window === 'undefined') return [];
  try {
    const existing = getCustomDietPlans();
    const filtered = existing.filter(p => p.id !== plan.id);
    const updated = [plan, ...filtered];
    localStorage.setItem(STORAGE_CUSTOM_DIETS_KEY, JSON.stringify(updated));
    return updated;
  } catch (e) {
    console.error('Error saving custom diet plan:', e);
    return [];
  }
}

export function deleteCustomDietPlan(planId: string): WeeklyDietPlan[] {
  if (typeof window === 'undefined') return [];
  try {
    const existing = getCustomDietPlans();
    const updated = existing.filter(p => p.id !== planId);
    localStorage.setItem(STORAGE_CUSTOM_DIETS_KEY, JSON.stringify(updated));
    return updated;
  } catch (e) {
    console.error('Error deleting custom diet plan:', e);
    return [];
  }
}

// Helper to generate a 7-day variation based on base meals
function make7DayPlan(
  planFocus: string,
  baseCalories: number,
  basePro: number,
  baseCarb: number,
  baseFat: number,
  mealTemplates: (dayIdx: number) => DietMeal[]
): DietDay[] {
  const dayNames = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
  const dayThemes = [
    'Kickoff & Lean Loading',
    'High Fiber & Gut Reset',
    'Midweek Metabolic Boost',
    'Plant & Greens Focus',
    'Peak Protein Velocity',
    'Millets & Functional Carbs',
    'Recovery & Light Detox',
  ];

  return dayNames.map((name, idx) => {
    const meals = mealTemplates(idx);
    const totalCalories = meals.reduce((s, m) => s + m.calories, 0);
    const totalProtein = Math.round(meals.reduce((s, m) => s + m.protein, 0) * 10) / 10;
    const totalCarbs = Math.round(meals.reduce((s, m) => s + m.carbs, 0) * 10) / 10;
    const totalFats = Math.round(meals.reduce((s, m) => s + m.fats, 0) * 10) / 10;

    return {
      dayName: name,
      focus: `${dayThemes[idx]} • ${planFocus}`,
      totalCalories,
      totalProtein,
      totalCarbs,
      totalFats,
      meals,
    };
  });
}

// --- PREPOPULATED 26 DIET PRESETS ---
export const PRESET_DIET_PLANS: WeeklyDietPlan[] = [
  // ==========================================
  // TAMIL NADU (5 Presets)
  // ==========================================
  {
    id: 'tn_lean_cut',
    name: 'Tamil Nadu Traditional Lean Cut (Keerai & Egg/Fish)',
    tagline: 'High-antioxidant Greens (Keerai), steamed Idlis, Rasam metabolism boosters and lean protein.',
    locality: 'tamilnadu',
    localityLabel: '🌴 Tamil Nadu',
    targetWeightLossRate: '0.5 kg / week',
    weeklyLossKg: 0.5,
    avgDailyCalories: 1550,
    avgDailyProtein: 88,
    avgDailyCarbs: 165,
    avgDailyFats: 38,
    dietType: 'Eggitarian',
    icon: '🥬',
    colorClass: 'text-emerald-400',
    borderClass: 'border-emerald-500/40',
    days: make7DayPlan('TN Keerai & Clean Cut', 1550, 88, 165, 38, (idx) => [
      {
        mealType: 'breakfast',
        name: idx % 2 === 0 ? 'Steamed Idlis with Veg Sambar & Chutney' : 'Egg White Paniyaram & Mint Thogayal',
        items: idx % 2 === 0 ? ['3 Soft Idlis', '1 bowl Veg Drumstick Sambar', '1 spoon Coconut-Mint Chutney'] : ['5 Egg White Chettinad Paniyaram', 'Tomato Thogayal', 'Black Filter Coffee'],
        portion: '1 plate',
        calories: 320,
        protein: 18,
        carbs: 48,
        fats: 5,
        icon: '⚪',
        tips: 'Idlis steamed without oil; fermentation promotes gut microbiome diversity.'
      },
      {
        mealType: 'snack_morning',
        name: 'Tender Coconut Water & Boiled Sundal',
        items: ['Fresh Elaneer (Tender Coconut)', '1 small cup Boiled White Chickpea Sundal'],
        portion: '1 serving',
        calories: 140,
        protein: 6,
        carbs: 22,
        fats: 2,
        icon: '🥥',
        tips: 'Rich in natural potassium to prevent muscle cramps.'
      },
      {
        mealType: 'lunch',
        name: idx % 2 === 0 ? 'Steamed Ponni Rice with Keerai Kootu & Boiled Eggs' : 'Brown Rice with Meen Kulambu (Fish Curry) & Poriyal',
        items: idx % 2 === 0 ? ['1 cup Steamed Rice (120g)', '1 big bowl Keerai (Spinach) Kootu with Moong', '2 Boiled Whole Eggs', '1 cup Pepper Rasam'] : ['1 cup Brown Rice', '1 bowl Tilapia/Vanjaram Fish Curry (no coconut paste)', '1 bowl Cabbage Beans Poriyal', 'Rasam'],
        portion: '1 full thali',
        calories: 520,
        protein: 34,
        carbs: 62,
        fats: 14,
        icon: '🍛',
        tips: 'Keerai provides iron and lutein; pepper rasam stimulates thermogenesis.'
      },
      {
        mealType: 'snack_evening',
        name: 'Roasted Makhana & Ginger Masala Chai',
        items: ['Roasted Lotus Seeds (Makhana) with pinch salt/pepper', '1 cup Low-Fat Milk Chai without sugar'],
        portion: '1 bowl',
        calories: 130,
        protein: 5,
        carbs: 18,
        fats: 3,
        icon: '☕',
      },
      {
        mealType: 'dinner',
        name: 'Oats Veg Dosa with Podi & Fresh Greek Curd',
        items: ['2 Rolled Oats & Moong Dosa', '1 cup Fresh Curd', 'Stir-fried Bottle Gourd (Suraikai)'],
        portion: '2 dosas',
        calories: 440,
        protein: 25,
        carbs: 45,
        fats: 14,
        icon: '🥞',
        tips: 'Light dinner consumed at least 2.5 hours before bedtime.'
      }
    ]),
  },
  {
    id: 'tn_kongu_protein',
    name: 'Kongu & Madurai High-Protein Non-Veg Split',
    tagline: 'Authentic Naatu Kozhi chicken broth, mutton chops, millets, and minimal seed oil.',
    locality: 'tamilnadu',
    localityLabel: '🌴 Tamil Nadu',
    targetWeightLossRate: '0.75 kg / week',
    weeklyLossKg: 0.75,
    avgDailyCalories: 1650,
    avgDailyProtein: 125,
    avgDailyCarbs: 130,
    avgDailyFats: 45,
    dietType: 'Non-Veg',
    icon: '🍗',
    colorClass: 'text-amber-400',
    borderClass: 'border-amber-500/40',
    days: make7DayPlan('Kongu Protein Hypertrophy', 1650, 125, 130, 45, (idx) => [
      {
        mealType: 'breakfast',
        name: 'Naatu Kozhi Clear Soup & Egg Kal Dosa',
        items: ['1 bowl Country Chicken clear bone soup', '2 Kal Dosa', '3 Boiled Egg Whites'],
        portion: '1 bowl + 2 dosas',
        calories: 360,
        protein: 32,
        carbs: 38,
        fats: 7,
        icon: '🥣',
        tips: 'Chicken broth contains bioavailable collagen and minerals.'
      },
      {
        mealType: 'snack_morning',
        name: 'Buttermilk (Neer Mor) with Curry Leaves & Hing',
        items: ['1 large glass churned buttermilk', 'Roasted peanuts (15g)'],
        portion: '1 glass',
        calories: 120,
        protein: 6,
        carbs: 8,
        fats: 6,
        icon: '🥛',
      },
      {
        mealType: 'lunch',
        name: 'Thinai (Foxtail Millet) with Madurai Mutton Chops & Rasam',
        items: ['1 cup Cooked Thinai Millet (140g)', '150g Lean Mutton cooked with shallots & pepper', '1 bowl Kootu', 'Poondu Rasam (Garlic Rasam)'],
        portion: '1 platter',
        calories: 590,
        protein: 48,
        carbs: 45,
        fats: 19,
        icon: '🥩',
        tips: 'Millet has a lower glycemic index than white rice and sustains satiety for 5+ hours.'
      },
      {
        mealType: 'snack_evening',
        name: 'Sprouted Green Gram (Pasi Payiru) Salad',
        items: ['1 cup Steamed sprouted moong', 'Grated carrot, cucumber & lemon squeeze'],
        portion: '1 cup',
        calories: 140,
        protein: 9,
        carbs: 22,
        fats: 1,
        icon: '🌱',
      },
      {
        mealType: 'dinner',
        name: 'Grilled Pepper Chicken Breast & Sautéed Beans',
        items: ['180g Grilled Chicken marinated in shallot pepper paste', '1 bowl Steamed French beans and carrots'],
        portion: '1 plate',
        calories: 440,
        protein: 40,
        carbs: 17,
        fats: 12,
        icon: '🍗',
      }
    ]),
  },
  {
    id: 'tn_chettinad_fatloss',
    name: 'Chettinad Balanced Weight-Loss (Red Rice & Fish)',
    tagline: 'Peppercorn, fennel, coriander spices accelerating metabolic fat oxidation with red rice.',
    locality: 'tamilnadu',
    localityLabel: '🌴 Tamil Nadu',
    targetWeightLossRate: '0.5 kg / week',
    weeklyLossKg: 0.5,
    avgDailyCalories: 1500,
    avgDailyProtein: 92,
    avgDailyCarbs: 155,
    avgDailyFats: 36,
    dietType: 'Non-Veg',
    icon: '🐟',
    colorClass: 'text-sky-400',
    borderClass: 'border-sky-500/40',
    days: make7DayPlan('Chettinad Red Rice & Spice', 1500, 92, 155, 36, () => [
      {
        mealType: 'breakfast',
        name: 'Kuzhi Paniyaram with Egg White Podi & Coconut Chutney',
        items: ['4 Paniyaram', '2 Whole Boiled Eggs with Idli Podi', 'Black Coffee'],
        portion: '1 plate',
        calories: 340,
        protein: 18,
        carbs: 42,
        fats: 8,
        icon: '🍳',
      },
      {
        mealType: 'snack_morning',
        name: 'Fresh Mosambi (Sweet Lime) & Almonds',
        items: ['1 whole Mosambi', '8 soaked almonds'],
        portion: '1 serving',
        calories: 120,
        protein: 4,
        carbs: 16,
        fats: 5,
        icon: '🍊',
      },
      {
        mealType: 'lunch',
        name: 'Chettinad Red Matta Rice with Spicy Fish Gravy & Poriyal',
        items: ['1 cup Cooked Red Rice (130g)', '160g Pomfret/Rohu Fish Curry', '1 cup Keerai Poriyal', 'Tomato Rasam'],
        portion: '1 thali',
        calories: 510,
        protein: 38,
        carbs: 55,
        fats: 12,
        icon: '🐟',
      },
      {
        mealType: 'snack_evening',
        name: 'Chana Sundal & Green Tea',
        items: ['1 bowl Black Chana Sundal (mustard tempered)', 'Green tea with lemon'],
        portion: '1 bowl',
        calories: 130,
        protein: 7,
        carbs: 20,
        fats: 2,
        icon: '🥣',
      },
      {
        mealType: 'dinner',
        name: 'Ragi Roti with Chicken Keema / Soya Keema',
        items: ['2 Thin Ragi (Finger Millet) Rotis', '1 bowl Minced Chicken or Soya Keema', 'Cucumber slices'],
        portion: '2 rotis + curry',
        calories: 400,
        protein: 29,
        carbs: 38,
        fats: 9,
        icon: '🫓',
      }
    ]),
  },
  {
    id: 'tn_chennai_deskworker',
    name: 'Chennai Corporate Desk-Worker Shred',
    tagline: 'Optimized for sedentary office professionals: blood sugar stabilization and zero afternoon slump.',
    locality: 'tamilnadu',
    localityLabel: '🌴 Tamil Nadu',
    targetWeightLossRate: '0.6 kg / week',
    weeklyLossKg: 0.6,
    avgDailyCalories: 1450,
    avgDailyProtein: 85,
    avgDailyCarbs: 145,
    avgDailyFats: 35,
    dietType: 'Veg',
    icon: '💻',
    colorClass: 'text-indigo-400',
    borderClass: 'border-indigo-500/40',
    days: make7DayPlan('Desk Worker Metabolism', 1450, 85, 145, 35, () => [
      {
        mealType: 'breakfast',
        name: 'Moong Dal Pongal with Roasted Paneer Bits',
        items: ['1 bowl Moong & Little Millet Pongal (minimal ghee)', '50g Grilled Low-Fat Paneer', 'Filter coffee with low-fat milk'],
        portion: '1 bowl',
        calories: 330,
        protein: 20,
        carbs: 42,
        fats: 8,
        icon: '🍚',
      },
      {
        mealType: 'snack_morning',
        name: 'Guava with Chaat Masala & Green Tea',
        items: ['1 medium Raw Guava sliced', 'Unsweetened green tea'],
        portion: '1 bowl',
        calories: 60,
        protein: 2,
        carbs: 14,
        fats: 0.5,
        icon: '🍐',
      },
      {
        mealType: 'lunch',
        name: 'Curd Rice Replacement: Cauliflower & Greek Yogurt with Dal',
        items: ['1 cup Riced Cauliflower & Greek Yogurt Thayir Sadam with pomegranate', '1 bowl Toor Dal Tadka', '1 cup Beans Poriyal'],
        portion: '1 bowl',
        calories: 450,
        protein: 28,
        carbs: 42,
        fats: 11,
        icon: '🥗',
        tips: 'Cauliflower substitution saves 180 kcal compared to white rice without losing traditional curd rice texture.'
      },
      {
        mealType: 'snack_evening',
        name: 'Boiled Egg Whites (3) / Roasted Peanuts',
        items: ['3 Boiled Egg Whites or 20g Roasted Peanuts', 'Lemon mint water'],
        portion: '1 snack',
        calories: 110,
        protein: 11,
        carbs: 4,
        fats: 3,
        icon: '🥚',
      },
      {
        mealType: 'dinner',
        name: 'Wheat Dosa with Vegetable Sambar & Flax Seeds',
        items: ['2 Whole Wheat Dosas (Godhumai)', '1 big bowl Mixed Vegetable Sambar', '1 spoon Ground Flaxseed topper'],
        portion: '2 dosas',
        calories: 400,
        protein: 18,
        carbs: 52,
        fats: 8,
        icon: '🥞',
      }
    ]),
  },
  {
    id: 'tn_sattvic_veg',
    name: 'Tamil Brahmin Sattvic High-Protein Veg Plan',
    tagline: 'Pure vegetarian diet with Mor Kuzhambu, Sundal, Paneer, high-calcium lentils, and no onion/garlic.',
    locality: 'tamilnadu',
    localityLabel: '🌴 Tamil Nadu',
    targetWeightLossRate: '0.4 kg / week',
    weeklyLossKg: 0.4,
    avgDailyCalories: 1520,
    avgDailyProtein: 82,
    avgDailyCarbs: 175,
    avgDailyFats: 36,
    dietType: 'Veg',
    icon: '🪔',
    colorClass: 'text-amber-300',
    borderClass: 'border-amber-400/40',
    days: make7DayPlan('Sattvic Lentil & Sundal', 1520, 82, 175, 36, () => [
      {
        mealType: 'breakfast',
        name: 'Adai (Mixed Lentil Crepe) with Avial Light',
        items: ['2 Adai (Chana, Moong, Toor dal)', '1 small bowl Light Vegetable Avial', '1 glass Neer Mor'],
        portion: '2 adais',
        calories: 360,
        protein: 19,
        carbs: 50,
        fats: 7,
        icon: '🥞',
      },
      {
        mealType: 'snack_morning',
        name: 'Sprouted Green Gram with Grated Coconut',
        items: ['1 cup Sprouted Pachai Payiru', '1 teaspoon fresh grated coconut'],
        portion: '1 cup',
        calories: 120,
        protein: 7,
        carbs: 18,
        fats: 2,
        icon: '🌱',
      },
      {
        mealType: 'lunch',
        name: 'Red Rice with Mor Kuzhambu & Vazhaikkai Poriyal',
        items: ['1 cup Red Rice', '1 bowl Buttermilk Mor Kuzhambu with Ash Gourd', '60g Sautéed Low-Fat Paneer', 'Coriander Rasam'],
        portion: '1 thali',
        calories: 520,
        protein: 26,
        carbs: 65,
        fats: 13,
        icon: '🥣',
      },
      {
        mealType: 'snack_evening',
        name: 'Karamani Sundal (Cowpeas) & Cardamom Chai',
        items: ['1 cup Boiled Red Cowpeas (Karamani)', 'Chai with skimmed milk'],
        portion: '1 bowl',
        calories: 140,
        protein: 8,
        carbs: 22,
        fats: 2,
        icon: '☕',
      },
      {
        mealType: 'dinner',
        name: 'Broken Wheat (Samba Rava) Upma & Curd',
        items: ['1.5 cup Samba Rava Upma with carrots & peas', '1 small cup Fresh homemade dahi'],
        portion: '1 plate',
        calories: 380,
        protein: 16,
        carbs: 54,
        fats: 8,
        icon: '🍲',
      }
    ]),
  },

  // ==========================================
  // TELUGU (ANDHRA & TELANGANA) (3 Presets)
  // ==========================================
  {
    id: 'telugu_gongura_chicken',
    name: 'Andhra Spicy High-Protein Non-Veg (Gongura & Ragi)',
    tagline: 'High-iron Gongura leaves, fiery steamed chicken, Ragi Sangati, and Egg Bhurji.',
    locality: 'telugu',
    localityLabel: '🌶️ Telugu (AP & TG)',
    targetWeightLossRate: '0.7 kg / week',
    weeklyLossKg: 0.7,
    avgDailyCalories: 1620,
    avgDailyProtein: 120,
    avgDailyCarbs: 135,
    avgDailyFats: 42,
    dietType: 'Non-Veg',
    icon: '🍗',
    colorClass: 'text-rose-400',
    borderClass: 'border-rose-500/40',
    days: make7DayPlan('Gongura Chicken & Ragi', 1620, 120, 135, 42, () => [
      {
        mealType: 'breakfast',
        name: 'Moong Dal Pesarattu with Ginger Pachadi & 2 Boiled Eggs',
        items: ['2 Pesarattu (whole moong crepes)', 'Allam Pachadi (ginger chutney)', '2 Boiled Eggs'],
        portion: '2 pesarattu + eggs',
        calories: 360,
        protein: 26,
        carbs: 38,
        fats: 9,
        icon: '🥞',
      },
      {
        mealType: 'snack_morning',
        name: 'Fresh Majjiga (Spiced Telugu Buttermilk)',
        items: ['1 tall glass Majjiga with ginger, green chilli & coriander'],
        portion: '300 ml',
        calories: 70,
        protein: 4,
        carbs: 6,
        fats: 2,
        icon: '🥛',
      },
      {
        mealType: 'lunch',
        name: 'Ragi Sangati with Andhra Gongura Chicken & Tomato Pappu',
        items: ['1 medium Ragi Sangati ball (Ragi & Rice)', '170g Gongura Chicken Curry', '1 cup Tomato Pappu (Dal)', 'Raw onion slices'],
        portion: '1 hearty plate',
        calories: 590,
        protein: 46,
        carbs: 52,
        fats: 16,
        icon: '🍛',
      },
      {
        mealType: 'snack_evening',
        name: 'Roasted Chana (Putnalu) & Black Coffee',
        items: ['30g Roasted Bengal Gram (Putnalu)', 'Black coffee'],
        portion: '1 handful',
        calories: 120,
        protein: 7,
        carbs: 17,
        fats: 3,
        icon: '☕',
      },
      {
        mealType: 'dinner',
        name: 'Egg White Tomato Bhurji & Multigrain Roti',
        items: ['4 Egg Whites scrambled with tomato, onion & spices', '2 Whole Wheat Rotis', 'Cucumber salad'],
        portion: '1 plate',
        calories: 420,
        protein: 32,
        carbs: 42,
        fats: 8,
        icon: '🍳',
      }
    ]),
  },
  {
    id: 'telangana_jowar_shred',
    name: 'Telangana Jowar & Pesara Pappu Fat Shred',
    tagline: 'Gluten-free Jowar (Sorghum) rotis, protein-dense Pesara Pappu, and roasted spices.',
    locality: 'telugu',
    localityLabel: '🌶️ Telugu (AP & TG)',
    targetWeightLossRate: '0.6 kg / week',
    weeklyLossKg: 0.6,
    avgDailyCalories: 1540,
    avgDailyProtein: 86,
    avgDailyCarbs: 160,
    avgDailyFats: 38,
    dietType: 'Veg',
    icon: '🌾',
    colorClass: 'text-amber-400',
    borderClass: 'border-amber-500/40',
    days: make7DayPlan('Jowar Roti & Pesara Pappu', 1540, 86, 160, 38, () => [
      {
        mealType: 'breakfast',
        name: 'Upma with Peanuts & Boiled Sprouts',
        items: ['1 bowl Rava/Millets Upma', 'Sprouted Moong Salad', '1 cup Black tea with lemon'],
        portion: '1 plate',
        calories: 320,
        protein: 14,
        carbs: 48,
        fats: 6,
        icon: '🥣',
      },
      {
        mealType: 'snack_morning',
        name: 'Spiced Pomegranate & Pumpkin Seeds',
        items: ['1 cup Fresh Pomegranate arils', '10g Raw pumpkin seeds'],
        portion: '1 bowl',
        calories: 140,
        protein: 5,
        carbs: 20,
        fats: 4,
        icon: '🍎',
      },
      {
        mealType: 'lunch',
        name: '2 Jowar Rotis with Pesara Pappu & Dondakaya Fry',
        items: ['2 Jowar Rotis (Sorghum)', '1 big bowl Moong Dal (Pesara Pappu)', '1 bowl Ivy Gourd (Dondakaya) stir fry', '1 cup Curd'],
        portion: '1 thali',
        calories: 550,
        protein: 29,
        carbs: 68,
        fats: 14,
        icon: '🫓',
      },
      {
        mealType: 'snack_evening',
        name: 'Spiced Boiled Peanut Sundal (Guggillu)',
        items: ['1 cup Boiled salted peanuts with mustard & green chillies'],
        portion: '1 cup',
        calories: 160,
        protein: 9,
        carbs: 12,
        fats: 9,
        icon: '🥜',
      },
      {
        mealType: 'dinner',
        name: 'Paneer Bhurji with Palak & 1 Multigrain Roti',
        items: ['80g Low-fat Paneer scrambled with spinach & cumin', '1 Multigrain Roti', 'Clear vegetable broth'],
        portion: '1 bowl + roti',
        calories: 370,
        protein: 24,
        carbs: 26,
        fats: 15,
        icon: '🧀',
      }
    ]),
  },
  {
    id: 'telugu_pesarattu_veg',
    name: 'Pesarattu & Soya High-Protein Vegetarian Protocol',
    tagline: 'Double moong dal focus, soya chunks curry, and leafy greens for lean muscle preservation.',
    locality: 'telugu',
    localityLabel: '🌶️ Telugu (AP & TG)',
    targetWeightLossRate: '0.5 kg / week',
    weeklyLossKg: 0.5,
    avgDailyCalories: 1480,
    avgDailyProtein: 95,
    avgDailyCarbs: 150,
    avgDailyFats: 32,
    dietType: 'Veg',
    icon: '🌱',
    colorClass: 'text-teal-400',
    borderClass: 'border-teal-500/40',
    days: make7DayPlan('Pesarattu & Soya Fuel', 1480, 95, 150, 32, () => [
      {
        mealType: 'breakfast',
        name: 'Whole Green Gram Pesarattu with Upma Filling (MLA Pesarattu Light)',
        items: ['2 Thin Pesarattus with light upma inside', 'Mint Coriander chutney', 'Black coffee'],
        portion: '2 pesarattus',
        calories: 340,
        protein: 22,
        carbs: 46,
        fats: 6,
        icon: '🥞',
      },
      {
        mealType: 'snack_morning',
        name: 'Fresh Coconut Water & Flax Seeds',
        items: ['1 glass tender coconut water', '1 spoon roasted flax seeds'],
        portion: '1 glass',
        calories: 90,
        protein: 3,
        carbs: 12,
        fats: 3,
        icon: '🥥',
      },
      {
        mealType: 'lunch',
        name: 'Brown Rice with Soya Chunks Curry & Palak Pappu',
        items: ['1 cup Brown Rice', '1 bowl Soya Chunks (50g dry) cooked in onion-tomato gravy', '1 cup Palak Spinach Dal', 'Fresh buttermilk'],
        portion: '1 thali',
        calories: 520,
        protein: 38,
        carbs: 58,
        fats: 9,
        icon: '🍲',
      },
      {
        mealType: 'snack_evening',
        name: 'Roasted Makhana with Turmeric & Salt',
        items: ['1 big bowl roasted makhana', 'Green tea'],
        portion: '1 bowl',
        calories: 110,
        protein: 4,
        carbs: 18,
        fats: 1.5,
        icon: '☕',
      },
      {
        mealType: 'dinner',
        name: 'Tofu Bhurji with 2 Phulkas & Cucumber Raita',
        items: ['120g Tofu scrambled with turmeric, cumin & peas', '2 Whole Wheat Phulkas', '1 cup Cucumber dahi raita'],
        portion: '1 plate',
        calories: 420,
        protein: 28,
        carbs: 42,
        fats: 12,
        icon: '🧀',
      }
    ]),
  },

  // ==========================================
  // KANNADA (KARNATAKA) (3 Presets)
  // ==========================================
  {
    id: 'kannada_bangalore_fit',
    name: 'Bangalore Fit & Lean (Ragi Mudde & Grilled Chicken)',
    tagline: 'Karnataka staple Ragi Mudde with nutrient-dense Sambar, chicken broth, and fresh salad.',
    locality: 'kannada',
    localityLabel: '🌿 Kannada (Karnataka)',
    targetWeightLossRate: '0.6 kg / week',
    weeklyLossKg: 0.6,
    avgDailyCalories: 1580,
    avgDailyProtein: 115,
    avgDailyCarbs: 140,
    avgDailyFats: 38,
    dietType: 'Non-Veg',
    icon: '⛰️',
    colorClass: 'text-emerald-400',
    borderClass: 'border-emerald-500/40',
    days: make7DayPlan('Ragi Mudde & Fit Chicken', 1580, 115, 140, 38, () => [
      {
        mealType: 'breakfast',
        name: 'Rava Idli with Coconut Chutney & Boiled Eggs',
        items: ['2 Steamed Rava Idlis (vegetable loaded)', '2 spoons Chutney', '3 Boiled Egg Whites'],
        portion: '1 plate',
        calories: 330,
        protein: 20,
        carbs: 42,
        fats: 7,
        icon: '⚪',
      },
      {
        mealType: 'snack_morning',
        name: 'Mosambi Juice (No Sugar) & Walnuts',
        items: ['1 glass fresh pressed sweet lime juice', '3 walnut halves'],
        portion: '1 glass',
        calories: 130,
        protein: 3,
        carbs: 18,
        fats: 5,
        icon: '🍊',
      },
      {
        mealType: 'lunch',
        name: '1 Traditional Ragi Mudde with Chicken Saaru & Greens Palya',
        items: ['1 medium Ragi Mudde (Finger millet ball)', '160g Country Chicken Saaru (thin curry)', '1 bowl Kosambari (cucumber & moong salad)', '1 cup Buttermilk'],
        portion: '1 plate',
        calories: 560,
        protein: 44,
        carbs: 52,
        fats: 14,
        icon: '🍛',
        tips: 'Ragi is extremely rich in calcium and complex starches with low glycemic spikes.'
      },
      {
        mealType: 'snack_evening',
        name: 'Sprouted Moong Kosambari',
        items: ['1 bowl Sprouted Moong with grated carrot, lemon & mustard tempering'],
        portion: '1 bowl',
        calories: 120,
        protein: 7,
        carbs: 18,
        fats: 2,
        icon: '🥗',
      },
      {
        mealType: 'dinner',
        name: 'Grilled Herb Chicken with Sautéed Beans & Carrots',
        items: ['170g Chicken Breast marinated in coriander-ginger paste', '1 cup Steamed French Beans & Broccoli'],
        portion: '1 plate',
        calories: 440,
        protein: 41,
        carbs: 16,
        fats: 11,
        icon: '🍗',
      }
    ]),
  },
  {
    id: 'kannada_jolada_rotti',
    name: 'North Karnataka Jolada Rotti Muscle Builder',
    tagline: 'Jowar flatbreads, Yennegai brinjal, Shenga (peanut) chutney podi, and boiled eggs.',
    locality: 'kannada',
    localityLabel: '🌿 Kannada (Karnataka)',
    targetWeightLossRate: '0.5 kg / week',
    weeklyLossKg: 0.5,
    avgDailyCalories: 1550,
    avgDailyProtein: 90,
    avgDailyCarbs: 165,
    avgDailyFats: 40,
    dietType: 'Eggitarian',
    icon: '🫓',
    colorClass: 'text-amber-400',
    borderClass: 'border-amber-500/40',
    days: make7DayPlan('Jolada Rotti & Shenga', 1550, 90, 165, 40, () => [
      {
        mealType: 'breakfast',
        name: 'Avalakki (Poha) with Sprouts & 2 Eggs',
        items: ['1 plate Pressed Rice Avalakki with roasted peanuts', '2 Boiled Eggs', 'Filter coffee'],
        portion: '1 plate',
        calories: 350,
        protein: 18,
        carbs: 45,
        fats: 9,
        icon: '🍳',
      },
      {
        mealType: 'snack_morning',
        name: 'Majjige (Karnataka Buttermilk) & Cucumber',
        items: ['1 glass buttermilk with asafoetida & curry leaves', 'Sliced cucumber'],
        portion: '1 serving',
        calories: 60,
        protein: 3,
        carbs: 6,
        fats: 1.5,
        icon: '🥛',
      },
      {
        mealType: 'lunch',
        name: '2 Jolada Rotti with Matki Dal, Yennegai & Curd',
        items: ['2 Thin Jolada Rotti (Jowar)', '1 bowl Sprouted Moth Beans (Matki) Usli', '1 small Stuffed Brinjal (Yennegai)', '1 bowl Homemade Curd', '1 spoon Shenga Chutney'],
        portion: '1 authentic thali',
        calories: 560,
        protein: 32,
        carbs: 68,
        fats: 16,
        icon: '🫓',
      },
      {
        mealType: 'snack_evening',
        name: 'Boiled Corn with Lemon & Black Pepper',
        items: ['1 cup Steamed sweet corn', 'Green tea'],
        portion: '1 cup',
        calories: 140,
        protein: 4,
        carbs: 26,
        fats: 1.5,
        icon: '🌽',
      },
      {
        mealType: 'dinner',
        name: 'Egg Bhurji with 2 Phulkas & Tomato Rasam',
        items: ['3 Whole Egg Bhurji with onions & green chillies', '2 Wheat Phulkas', '1 cup Karnataka Saaru'],
        portion: '1 plate',
        calories: 440,
        protein: 26,
        carbs: 42,
        fats: 14,
        icon: '🍳',
      }
    ]),
  },
  {
    id: 'kannada_udupi_veg',
    name: 'Udupi Vegetarian Clean Fuel (Bisi Bele & Neer Dosa)',
    tagline: 'High-fiber Bisi Bele Bath with sprouts, delicate Neer Dosa, and protein-packed Paneer Ghee Roast Light.',
    locality: 'kannada',
    localityLabel: '🌿 Kannada (Karnataka)',
    targetWeightLossRate: '0.4 kg / week',
    weeklyLossKg: 0.4,
    avgDailyCalories: 1500,
    avgDailyProtein: 80,
    avgDailyCarbs: 175,
    avgDailyFats: 38,
    dietType: 'Veg',
    icon: '🍲',
    colorClass: 'text-yellow-400',
    borderClass: 'border-yellow-500/40',
    days: make7DayPlan('Udupi Clean Vegetarian', 1500, 80, 175, 38, () => [
      {
        mealType: 'breakfast',
        name: 'Neer Dosa with Sprouted Moong Sagu',
        items: ['3 Light Neer Dosas', '1 bowl Vegetable Moong Sagu', 'Filter Coffee'],
        portion: '3 dosas',
        calories: 320,
        protein: 14,
        carbs: 48,
        fats: 6,
        icon: '🥞',
      },
      {
        mealType: 'snack_morning',
        name: 'Hesaru Bele Kosambari (Moong Salad)',
        items: ['1 bowl Soaked split yellow moong with cucumber, lemon & coriander'],
        portion: '1 bowl',
        calories: 120,
        protein: 7,
        carbs: 18,
        fats: 1,
        icon: '🥗',
      },
      {
        mealType: 'lunch',
        name: 'Nutrient-Dense Bisi Bele Bath with Sprouted Lentils & Boondi Raita',
        items: ['1.5 cup Bisi Bele Bath prepared with red rice, toor dal & beans', '80g Sautéed Low-Fat Paneer', '1 cup Cucumber Curd Raita'],
        portion: '1 bowl',
        calories: 520,
        protein: 28,
        carbs: 64,
        fats: 14,
        icon: '🍛',
      },
      {
        mealType: 'snack_evening',
        name: 'Roasted Chana & Cardamom Tea',
        items: ['30g Roasted Chickpeas', 'Tea with low-fat milk'],
        portion: '1 snack',
        calories: 140,
        protein: 7,
        carbs: 20,
        fats: 2.5,
        icon: '☕',
      },
      {
        mealType: 'dinner',
        name: 'Ragi Roti with Mixed Vegetable Palya & Fresh Dahi',
        items: ['2 Ragi Rotis with chopped onions & dill leaves (Sabbakki)', '1 bowl Cabbage Green Pea Palya', '1 cup Fresh Curd'],
        portion: '2 rotis',
        calories: 400,
        protein: 24,
        carbs: 52,
        fats: 10,
        icon: '🫓',
      }
    ]),
  },

  // ==========================================
  // GENERAL SOUTH INDIAN (5 Presets)
  // ==========================================
  {
    id: 'si_coastal_fish',
    name: 'South Indian Coastal High-Omega Fish & Rice Shred',
    tagline: 'Abundant Omega-3 EPA/DHA fatty acids from mackerel and sardines, tamarind rasam, and Kerala matta rice.',
    locality: 'south_general',
    localityLabel: '🥥 South Indian',
    targetWeightLossRate: '0.6 kg / week',
    weeklyLossKg: 0.6,
    avgDailyCalories: 1560,
    avgDailyProtein: 110,
    avgDailyCarbs: 145,
    avgDailyFats: 40,
    dietType: 'Non-Veg',
    icon: '🐟',
    colorClass: 'text-cyan-400',
    borderClass: 'border-cyan-500/40',
    days: make7DayPlan('Coastal Fish & Omega Split', 1560, 110, 145, 40, () => [
      {
        mealType: 'breakfast',
        name: 'Appam with Egg Roast (Minimal Oil)',
        items: ['2 Soft Appams (hopper)', '1 bowl Kerala Style Egg Roast (2 Eggs, shallots, tomato)', 'Black Tea'],
        portion: '2 appams + 2 eggs',
        calories: 350,
        protein: 20,
        carbs: 44,
        fats: 8,
        icon: '🍳',
      },
      {
        mealType: 'snack_morning',
        name: 'Tender Coconut & 6 Almonds',
        items: ['Fresh coconut water', '6 raw almonds'],
        portion: '1 serving',
        calories: 110,
        protein: 3,
        carbs: 12,
        fats: 5,
        icon: '🥥',
      },
      {
        mealType: 'lunch',
        name: 'Kerala Matta Rice with Ayala (Mackerel) Curry & Cabbage Thoran',
        items: ['1 cup Cooked Matta Rice (130g)', '180g Mackerel / Kingfish simmered in cocum gravy', '1 bowl Cabbage Coconut Thoran', 'Morru (spiced curd water)'],
        portion: '1 plate',
        calories: 550,
        protein: 42,
        carbs: 52,
        fats: 15,
        icon: '🐟',
      },
      {
        mealType: 'snack_evening',
        name: 'Boiled Chickpea Sundal & Green Tea',
        items: ['1 cup White Sundal with curry leaves', 'Green tea'],
        portion: '1 cup',
        calories: 140,
        protein: 7,
        carbs: 22,
        fats: 2,
        icon: '☕',
      },
      {
        mealType: 'dinner',
        name: 'Grilled Fish Tikka with Sautéed Greens & 1 Roti',
        items: ['160g Grilled Fish Tikka marinated in ginger, garlic & ajwain', '1 cup Sautéed spinach & bell peppers', '1 Wheat Phulka'],
        portion: '1 plate',
        calories: 410,
        protein: 38,
        carbs: 25,
        fats: 10,
        icon: '🐟',
      }
    ]),
  },
  {
    id: 'si_millet_cleanse',
    name: 'South Indian Vegan Millet Cleanse',
    tagline: '100% plant-based: Foxtail, Kodo, Barnyard millets, rich sambar, and moringa leaves.',
    locality: 'south_general',
    localityLabel: '🥥 South Indian',
    targetWeightLossRate: '0.5 kg / week',
    weeklyLossKg: 0.5,
    avgDailyCalories: 1460,
    avgDailyProtein: 78,
    avgDailyCarbs: 170,
    avgDailyFats: 32,
    dietType: 'Vegan',
    icon: '🌾',
    colorClass: 'text-emerald-400',
    borderClass: 'border-emerald-500/40',
    days: make7DayPlan('Millet & Moringa Vegan', 1460, 78, 170, 32, () => [
      {
        mealType: 'breakfast',
        name: 'Varagu (Kodo Millet) Idli with Moringa Dal Sambar',
        items: ['3 Kodo Millet Idlis', '1 big bowl Drumstick & Moringa leaves sambar', 'Tomato chutney'],
        portion: '3 idlis',
        calories: 320,
        protein: 15,
        carbs: 50,
        fats: 4,
        icon: '⚪',
      },
      {
        mealType: 'snack_morning',
        name: 'Roasted Pumpkin Seeds & Lemon Water',
        items: ['20g Raw pumpkin seeds', 'Warm lemon water'],
        portion: '1 cup',
        calories: 120,
        protein: 5,
        carbs: 6,
        fats: 8,
        icon: '🍋',
      },
      {
        mealType: 'lunch',
        name: 'Samai (Little Millet) with Chana Kootu & Beetroot Poriyal',
        items: ['1 cup Cooked Little Millet', '1 bowl Brown Chana & Yellow Moong Kootu', '1 cup Beetroot Poriyal', 'Jeera Rasam'],
        portion: '1 thali',
        calories: 510,
        protein: 26,
        carbs: 68,
        fats: 9,
        icon: '🍲',
      },
      {
        mealType: 'snack_evening',
        name: 'Steamed Sprouted Moong & Masala Chai (Oat Milk)',
        items: ['1 cup Sprouted green moong with chaat spices', 'Oat milk tea'],
        portion: '1 cup',
        calories: 140,
        protein: 8,
        carbs: 22,
        fats: 2,
        icon: '☕',
      },
      {
        mealType: 'dinner',
        name: 'Tofu Palak Bhurji & 2 Thin Jowar Rotis',
        items: ['140g Crumbled Tofu with Spinach & Cumin', '2 Jowar Rotis', 'Tomato cucumber salad'],
        portion: '1 plate',
        calories: 370,
        protein: 24,
        carbs: 38,
        fats: 11,
        icon: '🥗',
      }
    ]),
  },
  {
    id: 'si_egg_chicken_hypertrophy',
    name: 'South Indian Egg & Chicken Hypertrophy Diet',
    tagline: 'Targeted high-protein athletic recomp: 140g+ protein with classic South Indian spices.',
    locality: 'south_general',
    localityLabel: '🥥 South Indian',
    targetWeightLossRate: '0.75 kg / week',
    weeklyLossKg: 0.75,
    avgDailyCalories: 1720,
    avgDailyProtein: 145,
    avgDailyCarbs: 125,
    avgDailyFats: 42,
    dietType: 'Non-Veg',
    icon: '🥚',
    colorClass: 'text-amber-400',
    borderClass: 'border-amber-500/40',
    days: make7DayPlan('Egg & Chicken Hypertrophy', 1720, 145, 125, 42, () => [
      {
        mealType: 'breakfast',
        name: '4-Egg Omelette (2 whole, 2 whites) with 2 Dosa',
        items: ['4-Egg Omelette with onion, chillies & curry leaves', '2 Plain crisp dosas', 'Black filter coffee'],
        portion: '1 plate',
        calories: 420,
        protein: 34,
        carbs: 32,
        fats: 14,
        icon: '🍳',
      },
      {
        mealType: 'snack_morning',
        name: 'Whey Protein in Cold Water or Skimmed Milk',
        items: ['1 scoop Whey Protein Isolate (30g powder)', '1 glass cold water'],
        portion: '1 shake',
        calories: 120,
        protein: 25,
        carbs: 2,
        fats: 1,
        icon: '🥤',
      },
      {
        mealType: 'lunch',
        name: 'Steamed Brown Rice with 200g Kozhi Curry (Chicken) & Dal',
        items: ['1 cup Brown Rice (120g)', '200g Chicken Breast curry in South Indian onion-tomato gravy', '1 cup Moong dal kootu', 'Fresh buttermilk'],
        portion: '1 thali',
        calories: 580,
        protein: 52,
        carbs: 45,
        fats: 15,
        icon: '🍗',
      },
      {
        mealType: 'snack_evening',
        name: '3 Boiled Egg Whites & Green Tea',
        items: ['3 Boiled Egg Whites with black pepper and pinch of sea salt', 'Green tea'],
        portion: '3 egg whites',
        calories: 90,
        protein: 12,
        carbs: 1,
        fats: 0.5,
        icon: '🥚',
      },
      {
        mealType: 'dinner',
        name: 'Tawa Grilled Chicken Breast (180g) with Sautéed Veggies',
        items: ['180g Boneless Chicken Breast marinated in ginger-garlic and turmeric', '1 big bowl sautéed beans, capsicum and carrots'],
        portion: '1 platter',
        calories: 510,
        protein: 42,
        carbs: 15,
        fats: 12,
        icon: '🍗',
      }
    ]),
  },
  {
    id: 'si_low_glycemic_diabetic',
    name: 'South Indian Low-Glycemic & Insulin Stable Plan',
    tagline: 'Low sugar spikes: Methi greens, fenugreek water, bitter gourd, and high-protein lentils.',
    locality: 'south_general',
    localityLabel: '🥥 South Indian',
    targetWeightLossRate: '0.5 kg / week',
    weeklyLossKg: 0.5,
    avgDailyCalories: 1420,
    avgDailyProtein: 85,
    avgDailyCarbs: 135,
    avgDailyFats: 35,
    dietType: 'Veg',
    icon: '🛡️',
    colorClass: 'text-teal-400',
    borderClass: 'border-teal-500/40',
    days: make7DayPlan('Insulin Stable Low GI', 1420, 85, 135, 35, () => [
      {
        mealType: 'breakfast',
        name: 'Methi (Fenugreek) Leaves Moong Chilla & Curd',
        items: ['2 Moong dal pancakes loaded with fresh fenugreek leaves', '1 small cup low-fat curd', 'Warm water with soaked methi seeds'],
        portion: '2 chillas',
        calories: 310,
        protein: 18,
        carbs: 38,
        fats: 6,
        icon: '🥞',
      },
      {
        mealType: 'snack_morning',
        name: 'Sliced Jamun / Guava & Pumpkin Seeds',
        items: ['1 cup Fresh Jamun or Guava slices', '15g Raw seeds'],
        portion: '1 bowl',
        calories: 120,
        protein: 4,
        carbs: 16,
        fats: 5,
        icon: '🍐',
      },
      {
        mealType: 'lunch',
        name: 'Foxtail Millet with Pavakkai (Bitter Gourd) Poriyal & Sambar',
        items: ['1 cup Cooked Foxtail Millet (Thinai)', '1 bowl Sprouted Toor Dal Sambar', '1 bowl Bitter Gourd stir fry (Pavakkai)', '1 glass Neer Mor with hing'],
        portion: '1 thali',
        calories: 480,
        protein: 26,
        carbs: 58,
        fats: 10,
        icon: '🍛',
      },
      {
        mealType: 'snack_evening',
        name: 'Boiled Sprouted Fenugreek & Chana',
        items: ['1 bowl Sprouted kala chana with lemon & black salt', 'Cinnamon tea'],
        portion: '1 cup',
        calories: 130,
        protein: 8,
        carbs: 18,
        fats: 2,
        icon: '☕',
      },
      {
        mealType: 'dinner',
        name: 'Paneer & Spinach Bhurji with 1 Jowar Roti',
        items: ['100g Low-fat Paneer with 1 big bowl of palak', '1 Jowar Roti', 'Clear vegetable soup with pepper'],
        portion: '1 plate',
        calories: 380,
        protein: 29,
        carbs: 26,
        fats: 14,
        icon: '🧀',
      }
    ]),
  },
  {
    id: 'si_kerala_metabolic',
    name: 'Kerala Coconut & Seafood Balanced Metabolism',
    tagline: 'Authentic Meen Pollichathu, Kanthari chilli fat-burners, Matta rice, and light stew.',
    locality: 'south_general',
    localityLabel: '🥥 South Indian',
    targetWeightLossRate: '0.5 kg / week',
    weeklyLossKg: 0.5,
    avgDailyCalories: 1540,
    avgDailyProtein: 105,
    avgDailyCarbs: 145,
    avgDailyFats: 42,
    dietType: 'Non-Veg',
    icon: '🌴',
    colorClass: 'text-indigo-400',
    borderClass: 'border-indigo-500/40',
    days: make7DayPlan('Kerala Seafood & Cocum', 1540, 105, 145, 42, () => [
      {
        mealType: 'breakfast',
        name: 'Steamed Puttu (Red Rice) with Kadala Curry & 2 Egg Whites',
        items: ['1 piece Steamed Red Rice Puttu', '1 small bowl Black Chickpea Kadala Curry', '2 Boiled Egg Whites'],
        portion: '1 plate',
        calories: 340,
        protein: 18,
        carbs: 48,
        fats: 6,
        icon: '🥥',
      },
      {
        mealType: 'snack_morning',
        name: 'Spiced Buttermilk with Bird Eye Chilli (Kanthari)',
        items: ['1 glass Buttermilk blended with crushed Kanthari chilli, shallots and curry leaves'],
        portion: '1 tall glass',
        calories: 70,
        protein: 4,
        carbs: 6,
        fats: 2,
        icon: '🥛',
      },
      {
        mealType: 'lunch',
        name: 'Matta Rice with Meen Pollichathu (Wrapped Fish in Banana Leaf)',
        items: ['1 cup Kerala Matta Rice', '180g Pearl Spot (Karimeen) or Pomfret baked in banana leaf with onion-tomato paste', '1 bowl Moru Curry', 'Cucumber slices'],
        portion: '1 plate',
        calories: 550,
        protein: 44,
        carbs: 52,
        fats: 14,
        icon: '🐟',
      },
      {
        mealType: 'snack_evening',
        name: 'Roasted Cashews & Sulaimani Black Tea',
        items: ['15g Dry roasted cashews', '1 cup Sulaimani tea (black tea with cardamom and lemon)'],
        portion: '1 snack',
        calories: 130,
        protein: 4,
        carbs: 12,
        fats: 8,
        icon: '☕',
      },
      {
        mealType: 'dinner',
        name: 'Grilled Pepper Prawns / Fish with Sautéed Beans & 1 Phulka',
        items: ['170g Sautéed Tiger Prawns or Fish with black pepper and curry leaves', '1 cup Sautéed yardlong beans (Achinga)', '1 Wheat Phulka'],
        portion: '1 plate',
        calories: 450,
        protein: 35,
        carbs: 27,
        fats: 12,
        icon: '🦐',
      }
    ]),
  },

  // ==========================================
  // NORTH INDIAN (5 Presets)
  // ==========================================
  {
    id: 'ni_tandoori_lean',
    name: 'Delhi High-Protein Tandoori Chicken & Roti Cut',
    tagline: 'High-volume smoky tandoori chicken, whole wheat phulkas, dal tadka, and zero-oil salad.',
    locality: 'north',
    localityLabel: '🍲 North Indian',
    targetWeightLossRate: '0.75 kg / week',
    weeklyLossKg: 0.75,
    avgDailyCalories: 1650,
    avgDailyProtein: 135,
    avgDailyCarbs: 130,
    avgDailyFats: 38,
    dietType: 'Non-Veg',
    icon: '🍗',
    colorClass: 'text-rose-400',
    borderClass: 'border-rose-500/40',
    days: make7DayPlan('Tandoori Chicken & Lean Roti', 1650, 135, 130, 38, () => [
      {
        mealType: 'breakfast',
        name: 'Egg Bhurji (4 Whites, 1 Whole) with 2 Multigrain Toasts',
        items: ['5-Egg Scramble with onions, tomatoes & green chillies', '2 Slices 100% Whole Wheat Bread', 'Black coffee'],
        portion: '1 plate',
        calories: 360,
        protein: 30,
        carbs: 32,
        fats: 9,
        icon: '🍳',
      },
      {
        mealType: 'snack_morning',
        name: 'Spiced Buttermilk (Chaas) with Roasted Jeera',
        items: ['1 tall glass Chilled Chaas with mint and roasted cumin'],
        portion: '300 ml',
        calories: 70,
        protein: 4,
        carbs: 6,
        fats: 2,
        icon: '🥛',
      },
      {
        mealType: 'lunch',
        name: '2 Phulkas with 200g Tandoori Chicken Breast & Dal Tadka',
        items: ['200g Smoky Tandoori Chicken Breast (curd & spice marinade, baked/grilled)', '1 bowl Yellow Dal Tadka (light ghee tempering)', '2 Whole Wheat Phulkas', 'Green cucumber onion salad with lemon'],
        portion: '1 hearty thali',
        calories: 610,
        protein: 56,
        carbs: 48,
        fats: 14,
        icon: '🍗',
      },
      {
        mealType: 'snack_evening',
        name: 'Roasted Makhana & Ginger Green Tea',
        items: ['1 big bowl roasted lotus seeds with black salt', 'Ginger tea'],
        portion: '1 bowl',
        calories: 120,
        protein: 4,
        carbs: 20,
        fats: 2,
        icon: '☕',
      },
      {
        mealType: 'dinner',
        name: 'Grilled Chicken Tikka (160g) with Sautéed Bell Peppers',
        items: ['160g Chicken Tikka', '1 big bowl Sautéed bell peppers, onions and mushrooms in balsamic and herbs'],
        portion: '1 platter',
        calories: 490,
        protein: 41,
        carbs: 14,
        fats: 11,
        icon: '🍗',
      }
    ]),
  },
  {
    id: 'ni_punjabi_sattu_paneer',
    name: 'Punjabi Sattu, Paneer & Dal Makhani Light',
    tagline: 'High-protein roasted gram flour (Sattu) coolers, grilled paneer, and modified light dal makhani.',
    locality: 'north',
    localityLabel: '🍲 North Indian',
    targetWeightLossRate: '0.5 kg / week',
    weeklyLossKg: 0.5,
    avgDailyCalories: 1560,
    avgDailyProtein: 92,
    avgDailyCarbs: 160,
    avgDailyFats: 42,
    dietType: 'Veg',
    icon: '🥛',
    colorClass: 'text-amber-400',
    borderClass: 'border-amber-500/40',
    days: make7DayPlan('Sattu & Paneer Fuel', 1560, 92, 160, 42, () => [
      {
        mealType: 'breakfast',
        name: 'Sattu Namkeen Sharbat (High-Protein Drink) & Stuffed Paneer Paratha',
        items: ['1 tall glass Chana Sattu drink with black salt, lemon & roasted jeera (20g protein)', '1 Thin dry-roasted Paneer Paratha (no oil on griddle)'],
        portion: '1 drink + 1 paratha',
        calories: 390,
        protein: 26,
        carbs: 45,
        fats: 10,
        icon: '🥛',
      },
      {
        mealType: 'snack_morning',
        name: 'Sweet Seasonal Fruit & Pumpkin Seeds',
        items: ['1 Apple or 1 cup Papaya', '10g raw pumpkin seeds'],
        portion: '1 bowl',
        calories: 120,
        protein: 3,
        carbs: 20,
        fats: 4,
        icon: '🍎',
      },
      {
        mealType: 'lunch',
        name: '2 Phulkas with Light Dal Makhani (No Heavy Cream) & Grilled Paneer',
        items: ['1 bowl Black Urad & Rajma Dal cooked slowly with tomato puree and 1 tsp butter', '90g Grilled Paneer Tikka cubes', '2 Whole Wheat Phulkas', 'Radish (Mooli) & Cucumber salad'],
        portion: '1 thali',
        calories: 560,
        protein: 34,
        carbs: 58,
        fats: 18,
        icon: '🍲',
      },
      {
        mealType: 'snack_evening',
        name: 'Spiced Boiled Kala Chana Chaat',
        items: ['1 bowl Boiled Black Gram with chopped onion, tomato, green chillies & lemon'],
        portion: '1 cup',
        calories: 140,
        protein: 8,
        carbs: 22,
        fats: 2,
        icon: '🥣',
      },
      {
        mealType: 'dinner',
        name: 'Palak Paneer (Light) with 1 Multigrain Roti & Curd',
        items: ['1 bowl Spinach Paneer (pure spinach base, 70g paneer)', '1 Multigrain Roti', '1 small bowl Dahi'],
        portion: '1 bowl + roti',
        calories: 350,
        protein: 21,
        carbs: 28,
        fats: 14,
        icon: '🧀',
      }
    ]),
  },
  {
    id: 'ni_rajma_soya_pureveg',
    name: 'North Indian Pure Veg Soya Chaap & Rajma Engine',
    tagline: '100% vegetarian muscle builder: Punjabi Rajma Chawal, boiled soya chaap, and curd.',
    locality: 'north',
    localityLabel: '🍲 North Indian',
    targetWeightLossRate: '0.5 kg / week',
    weeklyLossKg: 0.5,
    avgDailyCalories: 1520,
    avgDailyProtein: 98,
    avgDailyCarbs: 160,
    avgDailyFats: 36,
    dietType: 'Veg',
    icon: '🫘',
    colorClass: 'text-emerald-400',
    borderClass: 'border-emerald-500/40',
    days: make7DayPlan('Rajma & Soya Muscle', 1520, 98, 160, 36, () => [
      {
        mealType: 'breakfast',
        name: 'Besan Chilla with Grated Paneer Filling',
        items: ['2 Gram flour (Besan) pancakes with onion & coriander', '50g Grated low-fat paneer inside', 'Green mint chutney'],
        portion: '2 chillas',
        calories: 350,
        protein: 22,
        carbs: 38,
        fats: 10,
        icon: '🥞',
      },
      {
        mealType: 'snack_morning',
        name: 'Fresh Chaas with Mint & Jeera',
        items: ['1 large glass homemade churned buttermilk with mint'],
        portion: '300 ml',
        calories: 70,
        protein: 4,
        carbs: 6,
        fats: 2,
        icon: '🥛',
      },
      {
        mealType: 'lunch',
        name: 'Brown Rice with Punjabi Rajma Masala & Sautéed Bhindi',
        items: ['1 cup Brown Rice (130g)', '1 big bowl Slow-cooked Red Kidney Beans (Rajma)', '1 cup Okra (Bhindi) Masala (light oil)', 'Cucumber onion tomato salad'],
        portion: '1 thali',
        calories: 520,
        protein: 28,
        carbs: 72,
        fats: 10,
        icon: '🫘',
      },
      {
        mealType: 'snack_evening',
        name: 'Roasted Soya Nuts & Green Tea',
        items: ['25g Roasted salted soya nuts', 'Green tea'],
        portion: '1 handful',
        calories: 140,
        protein: 12,
        carbs: 10,
        fats: 5,
        icon: '🥜',
      },
      {
        mealType: 'dinner',
        name: 'Grilled Soya Chaap (No Maida) with Mint Dip & 1 Roti',
        items: ['150g Grilled Soya Chaap marinated in tandoori spices and curd', '1 Whole Wheat Phulka', '1 bowl Clear vegetable soup'],
        portion: '1 plate',
        calories: 440,
        protein: 32,
        carbs: 34,
        fats: 9,
        icon: '🍢',
      }
    ]),
  },
  {
    id: 'ni_multigrain_clean_shred',
    name: 'North Indian Clean Shred (Multigrain & Paneer)',
    tagline: 'Calorie-deficit protocol: Jowar-Bajra-Wheat rotis, Moong dal, Lauki sabzi, and boiled egg/tofu.',
    locality: 'north',
    localityLabel: '🍲 North Indian',
    targetWeightLossRate: '0.6 kg / week',
    weeklyLossKg: 0.6,
    avgDailyCalories: 1450,
    avgDailyProtein: 90,
    avgDailyCarbs: 145,
    avgDailyFats: 34,
    dietType: 'Veg',
    icon: '🥗',
    colorClass: 'text-indigo-400',
    borderClass: 'border-indigo-500/40',
    days: make7DayPlan('Multigrain Clean Shred', 1450, 90, 145, 34, () => [
      {
        mealType: 'breakfast',
        name: 'Sprouted Moong & Oats Khichdi',
        items: ['1 big bowl Rolled Oats & Sprouted Moong Dal Khichdi (ghee tempered with cumin)', '1 cup Fresh Dahi'],
        portion: '1 bowl',
        calories: 330,
        protein: 19,
        carbs: 45,
        fats: 7,
        icon: '🍲',
      },
      {
        mealType: 'snack_morning',
        name: 'Seasonal Fruit & Soaked Almonds',
        items: ['1 medium Apple or Pomegranate', '6 Soaked and peeled almonds'],
        portion: '1 bowl',
        calories: 110,
        protein: 3,
        carbs: 18,
        fats: 4,
        icon: '🍎',
      },
      {
        mealType: 'lunch',
        name: '2 Multigrain Rotis with Yellow Dal & Ghia (Lauki) Sabzi',
        items: ['2 Multigrain Rotis (Wheat, Oats, Chana flour)', '1 bowl Yellow Moong Dal', '1 bowl Bottle Gourd (Lauki) cooked with cumin and tomato', '80g Low-fat Paneer cubes'],
        portion: '1 thali',
        calories: 510,
        protein: 32,
        carbs: 58,
        fats: 12,
        icon: '🫓',
      },
      {
        mealType: 'snack_evening',
        name: 'Roasted Chana & Lemon Water',
        items: ['30g Roasted Bengal Gram', 'Warm lemon water with pinch pink salt'],
        portion: '1 bowl',
        calories: 120,
        protein: 7,
        carbs: 18,
        fats: 2,
        icon: '🍋',
      },
      {
        mealType: 'dinner',
        name: 'Grilled Tofu or Paneer Salad with Mixed Greens',
        items: ['120g Grilled Paneer/Tofu with olive oil spritz', 'Mixed lettuce, cucumber, bell pepper and cherry tomatoes', '1 bowl Tomato coriander soup'],
        portion: '1 big bowl',
        calories: 380,
        protein: 29,
        carbs: 16,
        fats: 15,
        icon: '🥗',
      }
    ]),
  },
  {
    id: 'ni_pahadi_metabolism',
    name: 'Kashmiri & Pahadi Lean Metabolism (Kahwa & Trout)',
    tagline: 'Antioxidant saffron & almond Kahwa, grilled freshwater fish, kidney beans, and mountain greens.',
    locality: 'north',
    localityLabel: '🍲 North Indian',
    targetWeightLossRate: '0.5 kg / week',
    weeklyLossKg: 0.5,
    avgDailyCalories: 1500,
    avgDailyProtein: 102,
    avgDailyCarbs: 140,
    avgDailyFats: 38,
    dietType: 'Non-Veg',
    icon: '🏔️',
    colorClass: 'text-sky-400',
    borderClass: 'border-sky-500/40',
    days: make7DayPlan('Pahadi & Kahwa Metabolism', 1500, 102, 140, 38, () => [
      {
        mealType: 'breakfast',
        name: 'Saffron Almond Kahwa & Paneer Stuffed Roti',
        items: ['1 cup Authentic Kashmiri Kahwa (green tea with saffron, cinnamon, and slivered almonds)', '1 Thin Whole Wheat Roti stuffed with spiced paneer'],
        portion: '1 cup + 1 roti',
        calories: 320,
        protein: 18,
        carbs: 35,
        fats: 9,
        icon: '☕',
      },
      {
        mealType: 'snack_morning',
        name: 'Fresh Walnuts & Dried Apricots',
        items: ['4 Kashmiri walnut halves', '3 sun-dried apricots'],
        portion: '1 small snack',
        calories: 130,
        protein: 3,
        carbs: 14,
        fats: 8,
        icon: '🥜',
      },
      {
        mealType: 'lunch',
        name: 'Steamed Rice with Kashmiri Rajma & Saag (Collard Greens)',
        items: ['1 cup Steamed Rice (120g)', '1 bowl Kashmiri Red Rajma cooked with fennel & dry ginger (Sonth)', '1 bowl Kashmiri Haakh (collard greens simmered with mustard oil & chillies)', 'Fresh curd'],
        portion: '1 plate',
        calories: 510,
        protein: 28,
        carbs: 65,
        fats: 11,
        icon: '🍛',
      },
      {
        mealType: 'snack_evening',
        name: 'Noon Chai (Pink Salted Tea) / Green Tea with Roasted Makhana',
        items: ['1 cup Traditional Noon Chai or Green Tea', 'Roasted Makhana with pinch of salt'],
        portion: '1 cup',
        calories: 110,
        protein: 3,
        carbs: 18,
        fats: 2,
        icon: '☕',
      },
      {
        mealType: 'dinner',
        name: 'Grilled Herb Trout / Chicken Breast with Sautéed Haakh',
        items: ['170g Grilled Trout or Chicken Breast seasoned with Kashmiri red chilli and herbs', '1 bowl Sautéed mountain greens (spinach/collards)', '1 Wheat Phulka'],
        portion: '1 plate',
        calories: 430,
        protein: 50,
        carbs: 18,
        fats: 12,
        icon: '🐟',
      }
    ]),
  },

  // ==========================================
  // WESTERN / GLOBAL FITNESS (5 Presets)
  // ==========================================
  {
    id: 'western_classic_bodybuilder',
    name: 'Classic Bodybuilder Shred (Chicken, Rice & Broccoli)',
    tagline: 'The timeless physique cut: pure macro precision, ultra-low fat, and high thermic food effect.',
    locality: 'western',
    localityLabel: '🥑 Western & Global',
    targetWeightLossRate: '0.8 kg / week',
    weeklyLossKg: 0.8,
    avgDailyCalories: 1680,
    avgDailyProtein: 155,
    avgDailyCarbs: 145,
    avgDailyFats: 32,
    dietType: 'Non-Veg',
    icon: '🏋️',
    colorClass: 'text-amber-400',
    borderClass: 'border-amber-500/40',
    days: make7DayPlan('Bodybuilder Macro Cut', 1680, 155, 145, 32, () => [
      {
        mealType: 'breakfast',
        name: 'Egg White Omelette with Oats & Berries',
        items: ['5 Egg Whites + 1 Whole Egg scrambled', '40g Rolled Oats cooked in water with cinnamon', '1 handful fresh blueberries or sliced strawberries'],
        portion: '1 plate',
        calories: 360,
        protein: 34,
        carbs: 38,
        fats: 6,
        icon: '🍳',
      },
      {
        mealType: 'snack_morning',
        name: 'Whey Protein Shake with Cold Water',
        items: ['1 scoop Whey Protein Isolate (30g powder)', '300ml cold water'],
        portion: '1 shaker',
        calories: 120,
        protein: 26,
        carbs: 1,
        fats: 1,
        icon: '🥤',
      },
      {
        mealType: 'lunch',
        name: 'Grilled Chicken Breast, Basmati Rice & Steamed Broccoli',
        items: ['200g Grilled Chicken Breast seasoned with garlic powder, paprika & oregano', '150g Cooked Basmati Rice', '1.5 cups Steamed Broccoli with lemon squeeze'],
        portion: '1 meal prep bowl',
        calories: 550,
        protein: 52,
        carbs: 52,
        fats: 7,
        icon: '🍗',
      },
      {
        mealType: 'snack_evening',
        name: 'Cottage Cheese / Non-fat Greek Yogurt with Almonds',
        items: ['150g Low-fat Greek Yogurt or light paneer', '10g raw sliced almonds'],
        portion: '1 cup',
        calories: 160,
        protein: 18,
        carbs: 8,
        fats: 5,
        icon: '🍨',
      },
      {
        mealType: 'dinner',
        name: 'Seared White Fish / Tuna Steak with Asparagus & Sweet Potato',
        items: ['180g Baked Tilapia / Cod / Tuna steak', '100g Baked Sweet Potato cubes', '1 cup Grilled Asparagus or green beans'],
        portion: '1 plate',
        calories: 490,
        protein: 45,
        carbs: 36,
        fats: 8,
        icon: '🐟',
      }
    ]),
  },
  {
    id: 'western_keto_mediterranean',
    name: 'Keto Mediterranean Fat Burn (Salmon & Avocado)',
    tagline: 'Ketogenic metabolic state (<30g net carbs): Wild salmon, extra virgin olive oil, avocado, and spinach.',
    locality: 'western',
    localityLabel: '🥑 Western & Global',
    targetWeightLossRate: '0.75 kg / week',
    weeklyLossKg: 0.75,
    avgDailyCalories: 1650,
    avgDailyProtein: 105,
    avgDailyCarbs: 25,
    avgDailyFats: 125,
    dietType: 'Keto',
    icon: '🥑',
    colorClass: 'text-emerald-400',
    borderClass: 'border-emerald-500/40',
    days: make7DayPlan('Keto Mediterranean State', 1650, 105, 25, 125, () => [
      {
        mealType: 'breakfast',
        name: 'Keto Scrambled Eggs with Avocado & Spinach in Olive Oil',
        items: ['3 Whole Eggs scrambled in 1 tsp Extra Virgin Olive Oil', 'Half Hass Avocado sliced', '1 big handful baby spinach sautéed', 'Black Coffee with splash heavy cream'],
        portion: '1 plate',
        calories: 420,
        protein: 22,
        carbs: 4,
        fats: 35,
        icon: '🍳',
      },
      {
        mealType: 'snack_morning',
        name: 'Keto Walnuts & Macadamia Nuts',
        items: ['25g Raw Walnuts and Macadamias'],
        portion: '1 small handful',
        calories: 180,
        protein: 4,
        carbs: 2,
        fats: 18,
        icon: '🥜',
      },
      {
        mealType: 'lunch',
        name: 'Pan-Seared Atlantic Salmon with Greek Salad & Feta',
        items: ['170g Salmon Fillet with crispy skin', 'Mixed Greek salad: cucumber, olives, bell peppers, 30g Feta cheese', 'Drizzle of Extra Virgin Olive Oil and oregano'],
        portion: '1 bowl',
        calories: 580,
        protein: 40,
        carbs: 6,
        fats: 42,
        icon: '🐟',
      },
      {
        mealType: 'snack_evening',
        name: 'Celery Sticks with Almond Butter',
        items: ['3 Crisp Celery sticks', '1.5 tablespoon Unsweetened Almond Butter'],
        portion: '1 plate',
        calories: 150,
        protein: 4,
        carbs: 3,
        fats: 13,
        icon: '🥒',
      },
      {
        mealType: 'dinner',
        name: 'Grilled Herb Chicken Thighs with Garlic Parmesan Zucchini',
        items: ['180g Boneless skinless chicken thighs grilled with herbs', '2 cups Sautéed Zucchini ribbons with garlic and 1 spoon parmesan'],
        portion: '1 plate',
        calories: 420,
        protein: 38,
        carbs: 5,
        fats: 25,
        icon: '🍗',
      }
    ]),
  },
  {
    id: 'western_plantbased_vegan',
    name: 'Plant-Based Vegan High-Protein Athletic Protocol',
    tagline: 'Clean whole plant proteins: Edamame, tempeh, quinoa, lentils, chia seeds, and leafy greens.',
    locality: 'western',
    localityLabel: '🥑 Western & Global',
    targetWeightLossRate: '0.5 kg / week',
    weeklyLossKg: 0.5,
    avgDailyCalories: 1520,
    avgDailyProtein: 95,
    avgDailyCarbs: 165,
    avgDailyFats: 38,
    dietType: 'Vegan',
    icon: '🌱',
    colorClass: 'text-teal-400',
    borderClass: 'border-teal-500/40',
    days: make7DayPlan('Plant-Based High Protein', 1520, 95, 165, 38, () => [
      {
        mealType: 'breakfast',
        name: 'Overnight Protein Oats with Chia, Hemp Seeds & Berries',
        items: ['40g Rolled Oats soaked in unsweetened almond milk', '1 scoop Plant Protein (pea & brown rice)', '1 tablespoon Chia seeds', 'Half cup fresh berries'],
        portion: '1 mason jar',
        calories: 360,
        protein: 30,
        carbs: 42,
        fats: 9,
        icon: '🥣',
      },
      {
        mealType: 'snack_morning',
        name: 'Steamed Edamame in Pods with Sea Salt',
        items: ['1 cup Steamed Edamame (green soybeans) with coarse sea salt'],
        portion: '1 cup',
        calories: 140,
        protein: 12,
        carbs: 9,
        fats: 4,
        icon: '🫛',
      },
      {
        mealType: 'lunch',
        name: 'Warm Quinoa & Tempeh Power Bowl with Tahini Lemon Dressing',
        items: ['1 cup Cooked Quinoa', '140g Baked Marinated Tempeh strips', 'Steamed Kale, cucumber, grated carrot, and 1 tbsp light tahini dressing'],
        portion: '1 big power bowl',
        calories: 520,
        protein: 34,
        carbs: 56,
        fats: 14,
        icon: '🥗',
      },
      {
        mealType: 'snack_evening',
        name: 'Roasted Chickpeas & Green Tea',
        items: ['1 small bag Air-roasted crunchy chickpeas', 'Unsweetened green tea'],
        portion: '1 bowl',
        calories: 120,
        protein: 6,
        carbs: 18,
        fats: 2,
        icon: '☕',
      },
      {
        mealType: 'dinner',
        name: 'Lentil Vegetable Stew with Grilled Tofu',
        items: ['1 big bowl French green lentil stew with carrots, celery and herbs', '100g Firm Tofu seared on skillet with soy sauce & garlic'],
        portion: '1 deep bowl',
        calories: 380,
        protein: 26,
        carbs: 44,
        fats: 9,
        icon: '🍲',
      }
    ]),
  },
  {
    id: 'western_if_16_8',
    name: 'Intermittent Fasting 16:8 Lean Protocol',
    tagline: '16 hours fasting / 8 hours feeding window: Two nutrient-dense powerhouse meals + high-protein snack.',
    locality: 'western',
    localityLabel: '🥑 Western & Global',
    targetWeightLossRate: '0.7 kg / week',
    weeklyLossKg: 0.7,
    avgDailyCalories: 1580,
    avgDailyProtein: 130,
    avgDailyCarbs: 125,
    avgDailyFats: 48,
    dietType: 'Non-Veg',
    icon: '⏳',
    colorClass: 'text-purple-400',
    borderClass: 'border-purple-500/40',
    days: make7DayPlan('16:8 Fasting Protocol', 1580, 130, 125, 48, () => [
      {
        mealType: 'breakfast',
        name: 'Fasting Window (08:00 - 12:00): Hydration & Electrolytes',
        items: ['Black Coffee (no sugar, no milk)', 'Green Tea with lemon', '1 Litre Water with Himalayan pink salt pinch'],
        portion: 'Fasting',
        calories: 5,
        protein: 0,
        carbs: 1,
        fats: 0,
        icon: '💧',
        tips: 'Maintains low baseline insulin levels and stimulates autophagy and cellular cleanup.'
      },
      {
        mealType: 'lunch',
        name: 'Meal 1 (12:30 PM Fast Break): High Protein Chicken & Avocado Power Bowl',
        items: ['200g Grilled Chicken Breast', 'Half Avocado', '1 cup Cooked Brown Rice or Quinoa', 'Steamed green beans & cherry tomatoes', 'Apple Cider Vinegar drizzle'],
        portion: '1 large bowl',
        calories: 620,
        protein: 54,
        carbs: 52,
        fats: 19,
        icon: '🥑',
      },
      {
        mealType: 'snack_evening',
        name: 'Meal 2 (16:30 PM Mid-Window Fuel): Greek Yogurt & Mixed Nuts',
        items: ['180g Plain Non-fat Greek Yogurt', '1 scoop Whey Protein mixed in', '20g Raw Walnuts & Blueberries'],
        portion: '1 bowl',
        calories: 320,
        protein: 36,
        carbs: 18,
        fats: 11,
        icon: '🍨',
      },
      {
        mealType: 'dinner',
        name: 'Meal 3 (19:45 PM Window Close): Grilled Salmon & Sautéed Mediterranean Veggies',
        items: ['180g Wild Salmon Fillet', '2 cups Sautéed Zucchini, Bell Peppers, Mushrooms in 1 tsp olive oil', '1 small baked potato'],
        portion: '1 platter',
        calories: 630,
        protein: 40,
        carbs: 35,
        fats: 28,
        icon: '🐟',
        tips: 'Feeding window closes promptly at 20:00 PM.'
      }
    ]),
  },
  {
    id: 'western_paleo_conditioning',
    name: 'Paleo Whole Foods Athletic Conditioning',
    tagline: 'Grain-free, dairy-free clean fuel: Lean beef/chicken, sweet potatoes, eggs, nuts, and leafy greens.',
    locality: 'western',
    localityLabel: '🥑 Western & Global',
    targetWeightLossRate: '0.6 kg / week',
    weeklyLossKg: 0.6,
    avgDailyCalories: 1620,
    avgDailyProtein: 125,
    avgDailyCarbs: 120,
    avgDailyFats: 55,
    dietType: 'Non-Veg',
    icon: '🥩',
    colorClass: 'text-amber-500',
    borderClass: 'border-amber-500/40',
    days: make7DayPlan('Paleo Whole Foods', 1620, 125, 120, 55, () => [
      {
        mealType: 'breakfast',
        name: 'Paleo 3-Egg Frittata with Mushrooms & Spinach',
        items: ['3 Whole Organic Eggs baked/pan-cooked with sliced mushrooms, spinach, and red onion', 'Half sliced avocado', 'Black coffee'],
        portion: '1 plate',
        calories: 380,
        protein: 24,
        carbs: 6,
        fats: 28,
        icon: '🍳',
      },
      {
        mealType: 'snack_morning',
        name: 'Green Apple with Raw Almond Butter',
        items: ['1 Crisp Green Apple sliced', '1 tablespoon Pure Almond Butter'],
        portion: '1 bowl',
        calories: 170,
        protein: 4,
        carbs: 22,
        fats: 9,
        icon: '🍏',
      },
      {
        mealType: 'lunch',
        name: 'Grass-Fed Lean Beef / Chicken with Roasted Sweet Potato & Asparagus',
        items: ['170g Lean Minced Beef or Chicken Breast', '150g Oven-roasted sweet potato cubes (cinnamon & sea salt)', '1 cup Steamed Asparagus'],
        portion: '1 plate',
        calories: 540,
        protein: 45,
        carbs: 46,
        fats: 14,
        icon: '🥩',
      },
      {
        mealType: 'snack_evening',
        name: 'Hard-Boiled Eggs (2) with Sea Salt & Paprika',
        items: ['2 Whole Hard-boiled Eggs', 'Herbal tea'],
        portion: '2 eggs',
        calories: 140,
        protein: 12,
        carbs: 1,
        fats: 9,
        icon: '🥚',
      },
      {
        mealType: 'dinner',
        name: 'Grilled Herb Chicken Breast with Giant Spinach Salad & Olive Oil',
        items: ['180g Grilled Herb Chicken', 'Big Salad: 3 cups baby spinach, cucumber, sunflower seeds, olive oil and lemon vinaigrette'],
        portion: '1 large bowl',
        calories: 490,
        protein: 44,
        carbs: 12,
        fats: 22,
        icon: '🍗',
      }
    ]),
  },
];

// Recommendation Engine
export function recommendDietPlan(params: {
  locality?: string;
  weeklyLossKg?: number;
  age?: number;
  sex?: 'male' | 'female';
}): WeeklyDietPlan {
  const custom = getCustomDietPlans();
  const pool = [...PRESET_DIET_PLANS, ...custom];

  // Filter by locality first if chosen
  let filtered = pool;
  if (params.locality && params.locality !== 'all') {
    filtered = pool.filter(p => p.locality === params.locality);
    if (filtered.length === 0) filtered = pool;
  }

  // Filter or score by weeklyLossKg
  const targetLoss = params.weeklyLossKg || 0.5;
  const sorted = [...filtered].sort((a, b) => {
    const deltaA = Math.abs(a.weeklyLossKg - targetLoss);
    const deltaB = Math.abs(b.weeklyLossKg - targetLoss);
    return deltaA - deltaB;
  });

  return sorted[0] || PRESET_DIET_PLANS[0];
}
